services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: metro.proxy.rlwy.net
      DB_USER: root
      DB_PASSWORD: tFOTylFZMyakepOUsWOGmcAvMyKiQgcE
      DB_NAME: railway
      DB_PORT: 19655
      JWT_SECRET: mi_clave_secreta_muy_segura_2026
      REFRESH_SECRET: clave_refresh